-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

--autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "1920x1080@143",
    position = "auto",
    scale    = 1,
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "alacritty"

local fileManager = "dolphin"

local menu = "rofi -show drun"

local cursor = "hyprctl setcursor Simp1e-Dark 20"

local audio = "systemctl --user restart pipewire wireplumber pipewire-pulse"

local clip1 = "wl-paste --type text --watch cliphist store"

local clip2 = "wl-paste --type image --watch cliphist store"

local waybar = "~/.config/hypr/waybar/launch.sh"

local micro = "~/.config/hypr/micro.sh"

local wallpaper = "awww img ~/Pictures/Wallpaper/3.png"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:




--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("WLR_NO_HARDWARE_CURSORS", 1)

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 6,
        gaps_out = 8,
        border_size = 3,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(4b7054FF)", "rgba(b8b890ff)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 3,
        -- Change transparency of focused and unfocused windows
        active_opacity = 0.92,
        inactive_opacity = 0.8,
        shadow = {
            enabled = true,
            range = 6,
            render_power = 3,
            color = "rgba(00000066)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 8,
            passes = 2,
            noise = 0.02,
            contrast = 1.0,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        
        hl.curve("easeOutQuint", {type="bezier", points={{0.23, 1}, {0.32, 1}}}),
        hl.curve("easeInOutCubic", {type="bezier", points={{0.65, 0.05}, {0.36, 1}}}),
        hl.curve("linear", {type="bezier", points={{0, 0}, {1, 1}}}),
        hl.curve("almostLinear", {type="bezier", points={{0.5, 0.5}, {0.75, 1}}}),
        hl.curve("quick", {type="bezier", points={{0.15, 0}, {0.1, 1}}}),
        hl.curve("easeOut", {type="bezier", points={{0.22, 1}, {0.36, 1}}}),
        hl.curve("easeIn", {type="bezier", points={{0.36, 0}, {0.66, -0.56}}}),

        hl.animation({leaf= "global", enabled=true, speed=10, bezier="default"}),
        hl.animation({leaf= "windows", enabled=true, speed=7, bezier="easeOut", style="slide"}),
        hl.animation({leaf= "windowsIn", enabled=true, speed=5, bezier="easeOut", style="popin 80%"}),
        hl.animation({leaf= "windowsOut", enabled=true, speed=6, bezier="easeIn", style="popin 80%"}),
        hl.animation({leaf= "fadeIn", enabled=true, speed=1.73, bezier="almostLinear"}),
        hl.animation({leaf= "fadeOut", enabled=true, speed=1.46, bezier="almostLinear"}),
        hl.animation({leaf= "fade", enabled=true, speed=8, bezier="easeOut"}),
        hl.animation({leaf= "layers", enabled=true, speed=3.81, bezier="easeOutQuint"}),
        hl.animation({leaf= "layersIn", enabled=true, speed=4, bezier="easeOutQuint", style="fade"}),
        hl.animation({leaf= "layersOut", enabled=true, speed=1.5, bezier="linear", style="fade"}),
        hl.animation({leaf= "fadeLayersIn", enabled=true, speed=1.79, bezier="almostLinear"}),
        hl.animation({leaf= "fadeLayersOut", enabled=true, speed=1.39, bezier="almostLinear"}),
        hl.animation({leaf= "workspaces", enabled=true, speed=6, bezier="easeOut", style="slide"}),
        hl.animation({leaf= "workspacesIn", enabled=true, speed=3, bezier="easeOut", style="slidefade"}),
        hl.animation({leaf= "workspacesOut", enabled=true, speed=2, bezier="easeIn", style="slidefade"}),
        hl.animation({leaf= "zoomFactor", enabled=true, speed=7, bezier="quick"}),
    },
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrule = bordersize 0, floating:0, onworkspace:f[1]

-- windowrule = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        --    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = 1,
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us,ru",
        kb_options = "grp:alt_shift_toggle",
        follow_mouse = 1,
        accel_profile = "flat",
        sensitivity = 0.3,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures

-- TODO: manual review: gesture = 3, "horizontal", "workspace"

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("alacritty"))
hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "TAB", hl.dsp.exec_cmd("rofi -show drun"))

--bind = $mainMod, P, pseudo, # dwindle

--bind = $mainMod, J, togglesplit, # dwindle

hl.bind("SUPER + SHIFT + CONTROL" .. " + " .. "S", hl.dsp.exec_cmd("kill hyprpicker"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -z -m region --clipboard-only"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("hyprshot -z -m output --clipboard-only"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.exec_cmd("AyuGram"))
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("hyprctl --batch \"keyword decoration:active_opacity 1.0; keyword decoration:inactive_opacity 1.0\""))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("hyprctl --batch \"keyword decoration:active_opacity 0.92; keyword decoration:inactive_opacity 0.8\""))
hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. "R", hl.dsp.exec_cmd("~/.config/hypr/waybar/launch.sh"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("missioncenter"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Move windows

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.swap({ direction = "left" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.swap({ direction = "right" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.swap({ direction = "up" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.swap({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

-- bind = $mainMod, S, togglespecialworkspace, magic

-- bind = $mainMod SHIFT, S, movetoworkspace, special:magic

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. "Right", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. "Left", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. "Space", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.

--#windowrule = suppressevent maximize, class:.*

hl.window_rule({
    name  = "opacity_1",
    match = {
        class = "fullscreen 1",
    },
    opacity = 1,
})

--#windowrule = opacity 0.88, class:

-- Fix some dragging issues with XWayland

--#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("mako & ~/.config/hypr/waybar/launch.sh & hyprctl setcursor Simp1e-Dark 20 & systemctl --user restart pipewire wireplumber pipewire-pulse & awww-daemon & wl-paste --type text --watch cliphist store & wl-paste --type image --watch cliphist store & ~/.config/hypr/micro.sh & awww img ~/Pictures/Wallpaper/3.png & hypridle")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland")
end)
